/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    kotlin("jvm").version("1.3.40")
    application
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-csv:1.5")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.9.8")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.8")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.8")
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("com.github.ajalt:clikt:1.7.0")
    implementation("org.apache.commons:commons-text:1.6")
    implementation("us.codecraft:xsoup:0.3.1")
    implementation("org.jsoup:jsoup:1.11.3")
    implementation("io.github.erfangc:raincove-sdk:0.2.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.6")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.21")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.3.21")
    testImplementation("junit:junit:4.12")
}

group = "io.github.erfangc"
version = "0.1.0-SNAPSHOT"
description = "yahoo-finance-retriever"

application {
    mainClassName = "io.github.erfangc.yahoo.finance.parser.AppKt"
}
